sudo: false
language: python
cache: pip

matrix:
  include:
  - python: 3.5
    dist: xenial
    env: PY3.5
  - python: 3.6
    dist: xenial
    env: PY3.6
  allow_failures:
  - python: 3.4
    dist: xenial
    env: PY3.4

install:
    - pip install -r requirement.txt
    - pip install coveralls

script:
    - coverage run --source=./ ./manage.localy.py test

after_success:
    - coveralls
