language: python

python:
    - "3.5"

sudo: false

install:
    - pip install -r requirment.txt
    - pip install coveralls

script:
    - coverage run --source=./ ./manage.localy.py test

after_success:
    - coveralls

notifications:
    email: false
