language: python
cache: pip

python:
    - "3.5"
    - "3.6"
    - "3.7"

sudo: false

env:
    - DJANGO=2.0
    - DJANGO=2.1
    - DJANGO=master

matrix:
    fast_finish: true
    include:
      - { python: "3.6", env: DJANGO=master }
      - { python: "3.6", env: DJANGO=2.0 }
      - { python: "3.6", env: DJANGO=2.1 }

    exclude:
      - { python: "3.4", env: DJANGO=master }
      - { python: "3.4", env: DJANGO=2.1 }

    allow_failures:
      - env: DJANGO=master
      - env: DJANGO=2.1

install:
    - pip install -r requirment.txt

script:
    - coverage run ./manage.localy.py test

after_success:
    - pip install coveralls
    - coveralls

notifications:
    email: false
