language: python

python:
    - "3.5"
    - "3.6"
    - "3.4"

sudo: false

install:
    - pip install -r requirement.txt
    - pip install coveralls

script:
    - coverage run --source=./ ./manage.localy.py test

after_success:
    - coveralls
