language: python

python:
    - "3.5"

sudo: false

install:
    - pip install -r requirment.txt

script:
    - coverage run ./manage.localy.py test

after_success:
    - pip install coveralls
    - coveralls

notifications:
    email: false
