language: python


matrix:
  include:
  - python: 3.5
    dist: xenial
  - python: 3.6
    dist: xenial
  allow_failures:
  - python: 3.4
    dist: xenial

sudo: false

install:
    - pip install -r requirement.txt
    - pip install coveralls

script:
    - coverage run --source=./ ./manage.localy.py test

after_success:
    - coveralls
